version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: secure_db
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: secure_db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: secure_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "password123"]
    volumes:
      - ./cache:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge